### ISSUE TITLE
After login User should be directed to User Profile

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#175] opened 2017-07-13 09:13 UTC
Acceptance Criteria of #1147:
Users arrive at dashboard after login

**Comment by fuzzylogic2000** [comment] 2017-07-14 08:20
Yes, but that does not seem like a good idea. For example, if you're invited as a collaborator, click the link, have to log in first and after that you're redirected to the user profile, you'll then have to go back to the email to click the link again? To me that does not sound like intended behaviour?! 
I will close this issue now, please open again if importnant to you, @gereonrahnfeld

**Closed as completed by fuzzylogic2000** 2017-07-14 08:20 UTC
